name: Elixir CI

on:
  pull_request:
  push:
    branches: [ "main" ]
    
env:
  MIX_ENV: test
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        elixir: [1.14.3]
        otp: [25]
    
    services:
      db:
        image: postgres:15.2-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hanekawa_dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v3

    - name: Testing Env Vars
      run: echo ${#TEST_SECRET}
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
        
    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v3
      id: mix-caache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
 
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix deps.get
        
    - name: Run tests
      run: mix test
      
    - name: Check Formatting
      run: mix format --check-formatted
      
    - name: Compile project without warnings
      run: mix compile --warnings-as-errors
